language: java
jdk: oraclejdk8
script: mvn sonar:sonar -Dsonar.projectKey=barrouh_TextDiffCheckerDemo -Dsonar.organization=barrouh-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
notifications:
  email:
    recipients:
      - mohamed.barrouh@gmail.com
    on_success: never
    on_failure: always